### ISSUE TITLE
Why recommend include node_modules in a clean?

### ISSUE THREAD

**Issue by massfords** [trecloux/yeoman-maven-plugin#21]
Including the node_modules in the clean plugin is like including your local maven repo in a clean. You should remove this from your documentation.

**Comment by wuethrich44** [comment]
I agree with that. This setting slow down my build dramatically. 

@trecloux Do you have any reasonable reasons for that?

**Comment by trecloux** [comment]
From my point of view, the goal of the maven clean goal is to remove all files generated by the build.
Removing the *node_modules* ensure that the next `npm install` will start from a clean state.
For example if a dependency was installed manually, it will be removed and the build will only be based on declared dependencies.
Do you often launch a maven clean locally ?
